// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFVslexSLvOWOSymFG7qqvRm1f16sNI4w',
    appId: '1:714678217295:web:becd6adb1ee0aee671583a',
    messagingSenderId: '714678217295',
    projectId: 'carwash-and-service',
    authDomain: 'carwash-and-service.firebaseapp.com',
    storageBucket: 'carwash-and-service.appspot.com',
    measurementId: 'G-ZSRRBT44H8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHQa8hzIGO5uS91_sM9CnJ4QVVR_QGvO8',
    appId: '1:714678217295:android:f9f8418f08e51ae771583a',
    messagingSenderId: '714678217295',
    projectId: 'carwash-and-service',
    storageBucket: 'carwash-and-service.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtzrM1BXO_e7Tsv14t96_AL6GiiYminBg',
    appId: '1:714678217295:ios:c91497af8b09c60371583a',
    messagingSenderId: '714678217295',
    projectId: 'carwash-and-service',
    storageBucket: 'carwash-and-service.appspot.com',
    iosBundleId: 'com.example.carwashAndService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtzrM1BXO_e7Tsv14t96_AL6GiiYminBg',
    appId: '1:714678217295:ios:c91497af8b09c60371583a',
    messagingSenderId: '714678217295',
    projectId: 'carwash-and-service',
    storageBucket: 'carwash-and-service.appspot.com',
    iosBundleId: 'com.example.carwashAndService',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFVslexSLvOWOSymFG7qqvRm1f16sNI4w',
    appId: '1:714678217295:web:19d7c59762c1ced971583a',
    messagingSenderId: '714678217295',
    projectId: 'carwash-and-service',
    authDomain: 'carwash-and-service.firebaseapp.com',
    storageBucket: 'carwash-and-service.appspot.com',
    measurementId: 'G-M9JB0VMEE8',
  );
}
